// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: { path: "prisma/migrations" },

  // Prisma CLI uses THIS URL for migrations/introspection.
  // Must be the DIRECT (non-pooler) Neon URL.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});

